#!/usr/bin/env php
<?php

try {
    Phar::mapPhar('proophgen.phar');
    require_once 'phar://proophgen.phar/vendor/autoload.php';
} catch (PharException $e) {
    require_once __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

$application = new Application('proophgen', '0.1.6');

$application->add(new \Pilsniak\Command\DoCommand());
$application->add(new \Pilsniak\Command\ValueObjectCommand());
$application->add(new \Pilsniak\Command\CommandGeneratorCommand());
$application->add(new \Pilsniak\Command\AggregateRootCommand());
// ... register commands

$application->run();

__HALT_COMPILER();